backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
show_preview_links: false

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Nieuws"
    folder: "src/pages/nieuws"
    filter: {field: "templateKey", value: "blog-post"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Uitgelicht", name: "featuredpost", widget: "boolean", required: false, default: true}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/pages/index.md"
        label: "Hoofdpagina"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Opsomming, name: selling_points, widget: object, fields: [{label: Titel, name: title, widget: string}, {label: Punten, name: points, widget: list, field: {label: punt, name: text, widget: string} }]}
          - {label: Certificeringen, name: certifications, widget: object, fields: [{label: Titel, name: heading, widget: string}, {label: Beschrijving, name: description, widget: string}, {label: Certificeringen, name: certifications, widget: list, fields: [{label: Titel, name: product_title, widget: text},{label: Plaatje, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Fotos, name: main, widget: object, fields: [{label: Titel, name: heading, widget: string},{label: Foto1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Foto2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Foto3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/producten/index.md"
        label: "Producten"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Payot, name: payot, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Producten, name: products, widget: list, fields: [{label: Titel, name: product_title, widget: text},{label: Plaatje, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Overige, name: other, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Producten, name: products, widget: list, fields: [{label: Titel, name: product_title, widget: text},{label: Plaatje, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "src/pages/behandelingen/index.md"
        label: "Behandelignen"
        name: "treatments"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "treatment-page"}
          - {label: Titel, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Gezichtsbehandelingen, name: facial, widget: object, fields: [{label: Titel, name: title, widget: string}, {label: Behandelingen, name: treatments, widget: list, fields: [{label: Naam, name: title, widget: string},{label: Prijs, name: price, widget: number},{label: Duur, name: duration, widget: number},{label: Beschrijving, name: description, widget: text}]}]}
          - {label: Behandelingen, name: other, widget: object, fields: [{label: Titel, name: title, widget: string}, {label: Behandelingen, name: treatments, widget: list, fields: [{label: Naam, name: title, widget: string},{label: Prijs, name: price, widget: number},{label: Duur, name: duration, widget: number},{label: Beschrijving, name: description, widget: text}]}]}
          - {label: Ontharen, name: hairremoval, widget: list, fields: [{label: Behandeling, name: description, widget: string}, {label: Prijs, name: price, widget: number}]}
          - {label: Losse Behandelingen, name: single, widget: list, fields: [{label: Behandeling, name: description, widget: string}, {label: Prijs, name: price, widget: number}]}
      - file: "src/pages/nieuws/index.md"
        label: "Nieuws"
        name: "news"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-page"}
          - {label: Titel, name: title, widget: string}
          - {label: Plaatje, name: image, widget: image}
          - {label: Koptekst, name: header, widget: string}
          - {label: Beschrijving, name: description, widget: text}
  
  - name: "info"
    label: "Informatie"
    files:
      - file: "src/info/openinghours.md" 
        label: "Openingstijden"
        name: "openinghours"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "no-page-openinghours"}
          - {label: Dagen, name: openinghours, widget: list, fields: [{label: Dag, name: day, widget: string}, {label: van, name: from, widget: datetime, default: "", time_format: "HH:mm",date_format: false},{label: tot, name: to, widget: datetime, default: "", time_format: "HH:mm",date_format: false},{label: "Gesloten", name: "closed", widget: "boolean"}], allow_add: false}
